sudo: required
dist: trusty
language: minimal
branches:
  except:
    - template
env:
  global:
    - TRAVIS_USER_UID=$(id -u)
    - secure: "vc9+mklFoSFqW1Sg+4Jj+bInvKWXsZIqytBZTEXSYvdF/KD+ROWi8p+5A1YjqqNNPFIh9Q8lvL0N0rlhjTduerr3+6mC7A0qHCcmiUNYTgBYOrPk0wMM3kJnfcFX7YXz/o8fu8DamBIJeiD0i9JOh13srjmOJmdDolluOmFrAzgyhsSE9f2sSRYm9fbMmNqUCeForrsu8XntVSCchbH6D2bcZrFXdd2u5jvX6JowrH+t0tS+SaRL202lsfb0S7L78O7/fZjd19jblZ03nBF8rG+9LypfY7nv4yoowlpFojgYwg+Qbw5Swz2EVOV8YxaE1eeYNZHkSQjeQdn2vItchbjLvWKPestEayTYuT0qa7ACM7QljW86XZFR2SteLYVP9L4tDMHPJHAdAVkpTVlLaEpBCUS3ccrgvAZFuBkmaVzl0gAxsZkZBNiOGBHr8EIAGiycoRGWJ0foaKUboZkw1b1bLXLWYzJ+RWukd0Fbt1bu1kB3Yz+ErK4smxSY0ZwIpBNLbU7o0fThtJl/lZBycnW7tbrc6Q26i3g1wspDnGHQRZElOAqTpHHK6cm8Wev29SypWo/praUtfRHxMM3GQRmWNYkTO59Bq3dOCUgc5qx6fc0wwxyuTSCq/wMXe33twKOP7o5fjNHeQYg5+XGorLRKKUkS1moruEcX2w+1OGw="  # REMOTE

before_install:
  - openssl aes-256-cbc -K $encrypted_0f27bc85a100_key -iv $encrypted_0f27bc85a100_iv -in .travis/deploy-key.enc -out .travis/deploy-key -d

install:
  - sudo apt-get install sshfs
  - sudo .travis/install-alpine
  - sudo .travis/setup-alpine
script:
  - sudo .travis/buildrepo
