[redis]

# A string in the format `unix://path/to/redis.sock` or `tcp://host:port`.
URL = "unix:///run/redis/redis.sock"

# The database to connect to.
#DB = 0

# Only required if your redis instance is password-protected.
#Password = ""

# How long a redis read-command can take.
#ReadTimeout = "1s"

# How long the redis connection is to be kept alive without anything flowing
# through it.
#KeepAlivePeriod = "5m"

# How many idle connections can be in the redis-pool at once.
MaxIdle = 1

# How many connections the pool can keep.
MaxActive = 1

# Set if you use Sentinel.
#Sentinel = [ "tcp://sentinel1:23456", "tcp://sentinel2:23456" ]
#SentinelMaster = "mymaster"
